name: Chat Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.event_name == 'release' && github.event.action == 'published' && 'prod' || 'test' }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write 
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip


      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Debug - List directory contents
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of current directory:"
          ls -R
    
      - name: Set Startup Command (HR)
        run: |
          az webapp config set --name ${{ vars.HR_WEBAPP_NAME }} --resource-group ${{ vars.HR_RESOURCE_GROUP }} --startup-file "python3 -m gunicorn app:app"
        

      - name: Deploy to Azure Web App (HR)
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp-hr
        with:
          app-name: ${{ vars.HR_WEBAPP_NAME }}
          resource-group-name: ${{ vars.HR_RESOURCE_GROUP }}

      - name: Set App Settings (HR)
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ vars.HR_WEBAPP_NAME }}
          app-settings-json: ${{ steps.read_config.outputs.app_settings }}

# HMS Pipeline

      - name: Set Startup Command (HMS)
        run: |
          az webapp config set --name ${{ vars.HMS_WEBAPP_NAME }} --resource-group ${{ vars.HMS_RESOURCE_GROUP }} --startup-file "python3 -m gunicorn app:app"
          
  
      - name: Deploy to Azure Web App (HMS)
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp-hms
        with:
          app-name: ${{ vars.HMS_WEBAPP_NAME }}
          resource-group-name: ${{ vars.HMS_RESOURCE_GROUP }}

      - name: Set App Settings (HMS)
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ vars.HMS_WEBAPP_NAME }}
          app-settings-json: ${{ steps.read_config.outputs.app_settings }}


